name: AsciiDoc

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt -y update
          sudo apt -y install \
            bison \
            build-essential \
            cmake \
            curl \
            flex \
            fonts-lyx \
            graphviz \
            default-jre \
            libcairo2-dev \
            libffi-dev \
            libgdk-pixbuf2.0-dev \
            libglib2.0-dev \
            libpango1.0-dev \
            libxml2-dev \
            pkg-config \
            ruby \
            ruby-dev \
            libwebp-dev \
            libzstd-dev
          sudo gem install bundler
          sudo bundle install
          make foo/foo.all
          make bar/bar.all
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build/**
      - uses: actions/deploy-pages@v4
        id: deployment
